import Testing
import Foundation
@testable import ChotkiCore

/// Writes the Android launcher icon from the same geometry the Mac icon uses.
///
/// The alternative was tracing the mark by hand into path data, which is how a
/// logo ends up subtly different on one platform and nobody notices for a year.
/// The numbers live in `RopeMarkGeometry` and `CrossGeometry`; this turns them
/// into the one file format Android will accept for a launcher icon.
///
/// To regenerate after changing the mark: `CHOTKI_WRITE_CONTENT=1 swift test
/// --package-path core --filter IconExport`
@Suite("Icon export")
struct IconExportTests {

    /// Android's adaptive icon is a 108×108 canvas whose outer ring is masked
    /// away by whichever shape the launcher prefers. Content belongs in the
    /// middle 72; 68 leaves the mark a little air inside that.
    private static let canvas = 108.0
    private static let mark = 68.0
    private static let origin = (canvas - mark) / 2

    private static let path: String = {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent()
            .deletingLastPathComponent().deletingLastPathComponent()
            .appendingPathComponent("android/app/src/main/res/drawable/ic_launcher_foreground.xml")
            .path
    }()

    private func round(_ value: Double) -> String {
        String(format: "%.3f", value)
    }

    private func x(_ u: Double) -> Double { Self.origin + u * Self.mark }
    private func y(_ v: Double) -> Double { Self.origin + v * Self.mark }

    /// A circle, as the two half-arcs SVG path data requires.
    private func knot(cx: Double, cy: Double, r: Double) -> String {
        "M\(round(cx - r)),\(round(cy)) "
            + "a\(round(r)),\(round(r)) 0 1,0 \(round(r * 2)),0 "
            + "a\(round(r)),\(round(r)) 0 1,0 \(round(-r * 2)),0 Z"
    }

    private func rect(_ rx: Double, _ ry: Double, _ w: Double, _ h: Double) -> String {
        "M\(round(rx)),\(round(ry)) h\(round(w)) v\(round(h)) h\(round(-w)) Z"
    }

    private var pathData: String {
        var parts: [String] = []

        let r = RopeMarkGeometry.knotRadius * Self.mark
        for centre in RopeMarkGeometry.knotCentres {
            parts.append(knot(cx: x(centre.x), cy: y(centre.y), r: r))
        }

        // The cross, from the same bars and footrest the Mac draws.
        let box = RopeMarkGeometry.crossBox
        let cx = x(box.x), cy = y(box.y)
        let cw = box.width * Self.mark, ch = box.height * Self.mark
        for bar in CrossGeometry.bars {
            parts.append(rect(cx + bar.x * cw, cy + bar.y * ch, bar.width * cw, bar.height * ch))
        }
        let f = CrossGeometry.footrest
        parts.append(
            "M\(round(cx + f.leadingX * cw)),\(round(cy + f.leadingY * ch)) "
                + "L\(round(cx + f.trailingX * cw)),\(round(cy + f.trailingY * ch)) "
                + "L\(round(cx + f.trailingX * cw)),\(round(cy + (f.trailingY + f.thickness) * ch)) "
                + "L\(round(cx + f.leadingX * cw)),\(round(cy + (f.leadingY + f.thickness) * ch)) Z"
        )

        return parts.joined(separator: " ")
    }

    private var document: String {
        """
        <?xml version="1.0" encoding="utf-8"?>
        <!--
          Generated by IconExportTests in the Swift core. Do not edit by hand.
          The mark's proportions live in RopeMarkGeometry and CrossGeometry so
          that the Mac icon and this one are the same rope at different sizes.
        -->
        <vector xmlns:android="http://schemas.android.com/apk/res/android"
            android:width="108dp"
            android:height="108dp"
            android:viewportWidth="108"
            android:viewportHeight="108">
            <path
                android:fillColor="#C9A227"
                android:pathData="\(pathData)" />
        </vector>

        """
    }

    @Test("the committed launcher icon matches the mark")
    func committedIconMatches() throws {
        if ProcessInfo.processInfo.environment["CHOTKI_WRITE_CONTENT"] != nil {
            try FileManager.default.createDirectory(
                at: URL(fileURLWithPath: Self.path).deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            try document.write(toFile: Self.path, atomically: true, encoding: .utf8)
        }

        let committed = try String(contentsOfFile: Self.path, encoding: .utf8)
        #expect(committed == document, "the launcher icon is out of date — regenerate it")
    }

    @Test("the mark stays inside the safe zone")
    func staysInsideTheSafeZone() {
        // Anything outside the middle 72 can be cropped away by the launcher's
        // mask, and a cross with its foot cut off is worse than no icon.
        let r = RopeMarkGeometry.knotRadius * Self.mark
        var lowest = 0.0
        for centre in RopeMarkGeometry.knotCentres {
            #expect(x(centre.x) - r >= 18 && x(centre.x) + r <= 90)
            lowest = max(lowest, y(centre.y) + r)
        }
        let box = RopeMarkGeometry.crossBox
        lowest = max(lowest, y(box.y) + box.height * Self.mark)
        #expect(lowest <= 90, "the mark reaches \(lowest), past the safe zone")
        #expect(y(RopeMarkGeometry.centreY - RopeMarkGeometry.loopRadius) - r >= 18)
    }
}
