// Generated by tools/prepare-branding.py from Branding/version.json.
#define CHOTKI_FILE_VERSION 0,0,2,31
#define CHOTKI_FILE_VERSION_TEXT "0.0.2.31"
#define CHOTKI_PRODUCT_VERSION_TEXT "alpha-rc2-build31"
