// Generated by tools/prepare-branding.py from macos/version.env.
#define CHOTKI_FILE_VERSION 1,0,0,20030
#define CHOTKI_FILE_VERSION_TEXT "1.0.0.20030"
#define CHOTKI_PRODUCT_VERSION_TEXT "1.0 beta, build 30"
