package org.chotki.core

import java.time.ZoneId
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Differential test of the scoring engine against the Swift core.
 *
 * `scoring-parity.tsv` holds what the Swift engine made of a 141-day history
 * across six rules — 617 records, generated by a sequence reproduced exactly
 * here so the two are scoring the same thing rather than comparing generators.
 *
 * Worth doing because scoring is the one place with real arithmetic in it:
 * exponential decay past a thirty-day window, half credit for a late day, and
 * days stood down leaving both sides of the ratio. Every hand-written test in
 * the suite checks a property — "the score did not move", "half credit, not
 * zero" — and none of them would catch a decay curve that is subtly the wrong
 * shape. These ratios agree to nine decimal places or they do not agree.
 */
class ScoringParityTest {

    private val zone: ZoneId = ZoneId.of("Europe/London")
    private val now = CalendarDate.of(2026, 8, 20)!!.dueInstant(TimeOfDay.of(10, 0)!!, zone)!!
    private val start = CalendarDate.of(2026, 4, 1)!!

    /** The same deterministic sequence the fixture was generated from. */
    private class Sequence(private var seed: ULong = 12345uL) {
        fun next(): Int {
            seed = seed * 6364136223846793005uL + 1442695040888963407uL
            return ((seed shr 33) % 100uL).toInt()
        }
    }

    private fun history(): Triple<List<Rule>, List<Activation>, List<Occurrence>> {
        val shapes: List<Triple<String, Recurrence, TimeOfDay?>> = listOf(
            Triple("Morning prayers", Recurrence.Daily, TimeOfDay.of(6, 30)),
            Triple("Evening prayers", Recurrence.Daily, TimeOfDay.of(21, 30)),
            Triple("Jesus prayer", Recurrence.Daily, null),
            Triple(
                "Wed and Fri fast",
                Recurrence.Weekly(setOf(Weekday.WEDNESDAY, Weekday.FRIDAY)),
                null,
            ),
            Triple("Sunday Liturgy", Recurrence.Weekly(setOf(Weekday.SUNDAY)), TimeOfDay.of(9, 0)),
            Triple("Confession", Recurrence.Monthly(31), null),
        )

        val sequence = Sequence()
        val rules = mutableListOf<Rule>()
        val activations = mutableListOf<Activation>()
        val occurrences = mutableListOf<Occurrence>()

        for ((title, recurrence, time) in shapes) {
            val rule = Rule(title = title, recurrence = recurrence, timeOfDay = time)
            rules.add(rule)
            activations.add(Activation(ruleID = rule.id, from = start))
            for (offset in 0 until 141) {
                val date = start.plusDays(offset)
                val status = when (sequence.next()) {
                    in 0 until 55 -> OccurrenceStatus.COMPLETED
                    in 55 until 65 -> OccurrenceStatus.COMPLETED_LATE
                    in 65 until 72 -> OccurrenceStatus.SKIPPED
                    else -> null // nothing written: due, or missed once its moment passed
                }
                if (status != null) {
                    occurrences.add(Occurrence(ruleID = rule.id, date = date, status = status))
                }
            }
        }
        return Triple(rules, activations, occurrences)
    }

    private fun expected(): List<String> {
        val text = javaClass.getResourceAsStream("/scoring-parity.tsv")
            ?.bufferedReader()?.readText()
        assertNotNull(text, "the scoring parity fixture is missing")
        return text.trim().lines()
    }

    @Test
    fun `the generated history matches the one the fixture was made from`() {
        val (_, _, occurrences) = history()
        assertEquals(
            617, occurrences.size,
            "the sequence has drifted; the comparison below would be meaningless",
        )
    }

    @Test
    fun `every score agrees with the Swift engine to nine decimal places`() {
        val (rules, activations, occurrences) = history()
        val report = ScoringEngine(zone = zone).report(
            rules, activations, occurrences, start, CalendarDate.of(2026, 8, 31)!!, now,
        )

        val rows = expected().filter { !it.startsWith("OVERALL") && !it.startsWith("SUMMARY") }
        assertEquals(rows.size, report.perRule.size)

        for ((line, score) in rows.zip(report.perRule)) {
            val f = line.split('\t')
            assertEquals(f[0], score.title)
            assertEquals(f[1].toInt(), score.kept, "${score.title}: kept")
            assertEquals(f[2].toInt(), score.keptLate, "${score.title}: kept late")
            assertEquals(f[3].toInt(), score.missed, "${score.title}: missed")
            assertEquals(f[4].toInt(), score.stoodDown, "${score.title}: stood down")
            assertEquals(f[5].toInt(), score.streak, "${score.title}: streak")
            assertEquals(f[6], score.ratio?.let { "%.9f".format(it) } ?: "nil", "${score.title}: ratio")
        }
    }

    @Test
    fun `the overall figure agrees`() {
        val (rules, activations, occurrences) = history()
        val report = ScoringEngine(zone = zone).report(
            rules, activations, occurrences, start, CalendarDate.of(2026, 8, 31)!!, now,
        )
        val want = expected().first { it.startsWith("OVERALL") }.split('\t')[1]
        assertEquals(want, report.overall?.let { "%.9f".format(it) } ?: "nil")
    }

    // The words matter as much as the numbers: this is the part of the report
    // someone actually reads.
    @Test
    fun `the written summary is word for word the same`() {
        val (rules, activations, occurrences) = history()
        val report = ScoringEngine(zone = zone).report(
            rules, activations, occurrences, start, CalendarDate.of(2026, 8, 31)!!, now,
        )
        val want = expected().first { it.startsWith("SUMMARY") }.substringAfter('\t')
        assertEquals(want, report.summary.joinToString(" | "))
        assertTrue(report.summary.isNotEmpty())
    }
}
