#!/usr/bin/env python3
"""Generate Windows branding from canonical core geometry and macOS version."""
import json
from pathlib import Path
import re
import subprocess
import tempfile
from PIL import Image, ImageDraw

root = Path(__file__).resolve().parents[2]
output = root / "windows/Branding"
output.mkdir(exist_ok=True)
geometry = root / "core/Sources/ChotkiCore/Presentation"
with tempfile.TemporaryDirectory(prefix="chotki-branding-") as directory:
    temporary = Path(directory)
    main = temporary / "main.swift"
    main.write_text('''import Foundation
let box = RopeMarkGeometry.crossBox
let foot = CrossGeometry.footrest
let data: [String: Any] = [
    "knots": RopeMarkGeometry.knotCentres.map { [$0.x, $0.y, RopeMarkGeometry.knotRadius] },
    "bars": CrossGeometry.bars.map { [box.x + $0.x * box.width, box.y + $0.y * box.height, $0.width * box.width, $0.height * box.height] },
    "foot": [(foot.leadingX, foot.leadingY), (foot.trailingX, foot.trailingY), (foot.trailingX, foot.trailingY + foot.thickness), (foot.leadingX, foot.leadingY + foot.thickness)].map { [box.x + $0.0 * box.width, box.y + $0.1 * box.height] }
]
print(String(data: try JSONSerialization.data(withJSONObject: data), encoding: .utf8)!)
''')
    executable = temporary / "geometry"
    subprocess.run(["swiftc", "-module-cache-path", str(temporary / "cache"),
                    str(geometry / "CrossGeometry.swift"), str(geometry / "RopeMarkGeometry.swift"),
                    str(main), "-o", str(executable)], check=True)
    mark = json.loads(subprocess.check_output([str(executable)], text=True))

# The macOS appIcon's rounded ground, margin and colors, rendered from vectors.
side = 2048
image = Image.new("RGBA", (side, side), (0, 0, 0, 0))
draw = ImageDraw.Draw(image)
inset = side * .047
draw.rounded_rectangle((inset, inset, side-inset, side-inset), radius=side*.203, fill=(21, 22, 28, 255))
def point(x, y):
    return (side * (.14 + x * .72), side * (.14 + y * .72))
gold = (201, 162, 39, 255)
for x, y, radius in mark["knots"]:
    draw.ellipse((*point(x-radius, y-radius), *point(x+radius, y+radius)), fill=gold)
for x, y, width, height in mark["bars"]:
    draw.rectangle((*point(x, y), *point(x+width, y+height)), fill=gold)
draw.polygon([point(x, y) for x, y in mark["foot"]], fill=gold)
image.resize((1024, 1024), Image.Resampling.LANCZOS).save(output / "Chotki.ico", format="ICO",
                    sizes=[(16,16), (24,24), (32,32), (48,48), (64,64), (128,128), (256,256)])
version = dict(re.findall(r'^(CHOTKI_\w+)=(.*)$', (root / "macos/version.env").read_text(), re.MULTILINE))
marketing = version["CHOTKI_MARKETING_VERSION"].strip('"')
parts = marketing.split('.')
if len(parts) > 3 or any(not part.isdecimal() for part in parts):
    raise ValueError("Expected a numeric macOS marketing version")
numeric = [int(part) for part in parts] + [0] * (3-len(parts)) + [int(version["CHOTKI_BUNDLE_VERSION"].strip('"'))]
if any(part > 65535 for part in numeric):
    raise ValueError("Windows version components must fit sixteen bits")
display = version["CHOTKI_VERSION"].strip('"')
(output / "Version.h").write_text('// Generated by tools/prepare-branding.py from macos/version.env.\n'
    + '#define CHOTKI_FILE_VERSION ' + ','.join(map(str, numeric)) + '\n'
    + '#define CHOTKI_FILE_VERSION_TEXT ' + json.dumps('.'.join(map(str, numeric))) + '\n'
    + '#define CHOTKI_PRODUCT_VERSION_TEXT ' + json.dumps(display) + '\n')
print("Prepared canonical Windows icon and " + display + ".")
